//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\AutoStepLexer.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AutoStep.Compiler.Parser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class AutoStepLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		FEATURE=1, SCENARIO=2, BACKGROUND=3, TAG=4, OPTION=5, NEWLINE=6, WORD=7, 
		WS=8, TEXT_COMMENT=9, GIVEN=10, WHEN=11, THEN=12, AND=13;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"FEATURE", "SCENARIO", "BACKGROUND", "TAG", "OPTION", "NEWLINE", "WORD", 
		"WS", "TEXT_COMMENT", "GIVEN", "WHEN", "THEN", "AND"
	};


	public AutoStepLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public AutoStepLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'Feature:'", "'Scenario:'", "'Background:'", null, null, null, 
		null, null, null, "'Given '", "'When '", "'Then '", "'And '"
	};
	private static readonly string[] _SymbolicNames = {
		null, "FEATURE", "SCENARIO", "BACKGROUND", "TAG", "OPTION", "NEWLINE", 
		"WORD", "WS", "TEXT_COMMENT", "GIVEN", "WHEN", "THEN", "AND"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "AutoStepLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static AutoStepLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\xF', '\x88', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', 
		'@', '\n', '\x5', '\f', '\x5', '\xE', '\x5', '\x43', '\v', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', 'H', '\n', '\x6', '\f', 
		'\x6', '\xE', '\x6', 'K', '\v', '\x6', '\x3', '\a', '\a', '\a', 'N', '\n', 
		'\a', '\f', '\a', '\xE', '\a', 'Q', '\v', '\a', '\x3', '\a', '\x5', '\a', 
		'T', '\n', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x6', '\b', 'Y', 
		'\n', '\b', '\r', '\b', '\xE', '\b', 'Z', '\x3', '\t', '\x6', '\t', '^', 
		'\n', '\t', '\r', '\t', '\xE', '\t', '_', '\x3', '\n', '\a', '\n', '\x63', 
		'\n', '\n', '\f', '\n', '\xE', '\n', '\x66', '\v', '\n', '\x3', '\n', 
		'\x3', '\n', '\a', '\n', 'j', '\n', '\n', '\f', '\n', '\xE', '\n', 'm', 
		'\v', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x2', '\x2', '\xF', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', 
		'\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', 
		'\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x3', '\x2', '\a', 
		'\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x5', '\x2', '\f', 
		'\f', '\xF', '\xF', '%', '%', '\x4', '\x2', '\v', '\v', '\"', '\"', '\x6', 
		'\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '%', '%', '\x4', '\x2', '\f', 
		'\f', '\xF', '\xF', '\x2', '\x8F', '\x2', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x5', '&', '\x3', '\x2', '\x2', 
		'\x2', '\a', '\x30', '\x3', '\x2', '\x2', '\x2', '\t', '<', '\x3', '\x2', 
		'\x2', '\x2', '\v', '\x44', '\x3', '\x2', '\x2', '\x2', '\r', 'O', '\x3', 
		'\x2', '\x2', '\x2', '\xF', 'X', '\x3', '\x2', '\x2', '\x2', '\x11', ']', 
		'\x3', '\x2', '\x2', '\x2', '\x13', '\x64', '\x3', '\x2', '\x2', '\x2', 
		'\x15', 'p', '\x3', '\x2', '\x2', '\x2', '\x17', 'w', '\x3', '\x2', '\x2', 
		'\x2', '\x19', '}', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x83', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', '\x1E', '\a', 'H', '\x2', '\x2', '\x1E', 
		'\x1F', '\a', 'g', '\x2', '\x2', '\x1F', ' ', '\a', '\x63', '\x2', '\x2', 
		' ', '!', '\a', 'v', '\x2', '\x2', '!', '\"', '\a', 'w', '\x2', '\x2', 
		'\"', '#', '\a', 't', '\x2', '\x2', '#', '$', '\a', 'g', '\x2', '\x2', 
		'$', '%', '\a', '<', '\x2', '\x2', '%', '\x4', '\x3', '\x2', '\x2', '\x2', 
		'&', '\'', '\a', 'U', '\x2', '\x2', '\'', '(', '\a', '\x65', '\x2', '\x2', 
		'(', ')', '\a', 'g', '\x2', '\x2', ')', '*', '\a', 'p', '\x2', '\x2', 
		'*', '+', '\a', '\x63', '\x2', '\x2', '+', ',', '\a', 't', '\x2', '\x2', 
		',', '-', '\a', 'k', '\x2', '\x2', '-', '.', '\a', 'q', '\x2', '\x2', 
		'.', '/', '\a', '<', '\x2', '\x2', '/', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'\x30', '\x31', '\a', '\x44', '\x2', '\x2', '\x31', '\x32', '\a', '\x63', 
		'\x2', '\x2', '\x32', '\x33', '\a', '\x65', '\x2', '\x2', '\x33', '\x34', 
		'\a', 'm', '\x2', '\x2', '\x34', '\x35', '\a', 'i', '\x2', '\x2', '\x35', 
		'\x36', '\a', 't', '\x2', '\x2', '\x36', '\x37', '\a', 'q', '\x2', '\x2', 
		'\x37', '\x38', '\a', 'w', '\x2', '\x2', '\x38', '\x39', '\a', 'p', '\x2', 
		'\x2', '\x39', ':', '\a', '\x66', '\x2', '\x2', ':', ';', '\a', '<', '\x2', 
		'\x2', ';', '\b', '\x3', '\x2', '\x2', '\x2', '<', '=', '\a', '\x42', 
		'\x2', '\x2', '=', '\x41', '\n', '\x2', '\x2', '\x2', '>', '@', '\n', 
		'\x3', '\x2', '\x2', '?', '>', '\x3', '\x2', '\x2', '\x2', '@', '\x43', 
		'\x3', '\x2', '\x2', '\x2', '\x41', '?', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'\x42', '\x3', '\x2', '\x2', '\x2', '\x42', '\n', '\x3', '\x2', '\x2', 
		'\x2', '\x43', '\x41', '\x3', '\x2', '\x2', '\x2', '\x44', '\x45', '\a', 
		'&', '\x2', '\x2', '\x45', 'I', '\n', '\x2', '\x2', '\x2', '\x46', 'H', 
		'\n', '\x3', '\x2', '\x2', 'G', '\x46', '\x3', '\x2', '\x2', '\x2', 'H', 
		'K', '\x3', '\x2', '\x2', '\x2', 'I', 'G', '\x3', '\x2', '\x2', '\x2', 
		'I', 'J', '\x3', '\x2', '\x2', '\x2', 'J', '\f', '\x3', '\x2', '\x2', 
		'\x2', 'K', 'I', '\x3', '\x2', '\x2', '\x2', 'L', 'N', '\t', '\x4', '\x2', 
		'\x2', 'M', 'L', '\x3', '\x2', '\x2', '\x2', 'N', 'Q', '\x3', '\x2', '\x2', 
		'\x2', 'O', 'M', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\x3', '\x2', '\x2', 
		'\x2', 'P', 'S', '\x3', '\x2', '\x2', '\x2', 'Q', 'O', '\x3', '\x2', '\x2', 
		'\x2', 'R', 'T', '\a', '\xF', '\x2', '\x2', 'S', 'R', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'T', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'V', '\a', '\f', '\x2', '\x2', 'V', '\xE', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'Y', '\n', '\x5', '\x2', '\x2', 'X', 'W', '\x3', '\x2', '\x2', 
		'\x2', 'Y', 'Z', '\x3', '\x2', '\x2', '\x2', 'Z', 'X', '\x3', '\x2', '\x2', 
		'\x2', 'Z', '[', '\x3', '\x2', '\x2', '\x2', '[', '\x10', '\x3', '\x2', 
		'\x2', '\x2', '\\', '^', '\t', '\x4', '\x2', '\x2', ']', '\\', '\x3', 
		'\x2', '\x2', '\x2', '^', '_', '\x3', '\x2', '\x2', '\x2', '_', ']', '\x3', 
		'\x2', '\x2', '\x2', '_', '`', '\x3', '\x2', '\x2', '\x2', '`', '\x12', 
		'\x3', '\x2', '\x2', '\x2', '\x61', '\x63', '\t', '\x4', '\x2', '\x2', 
		'\x62', '\x61', '\x3', '\x2', '\x2', '\x2', '\x63', '\x66', '\x3', '\x2', 
		'\x2', '\x2', '\x64', '\x62', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', 
		'\x3', '\x2', '\x2', '\x2', '\x65', 'g', '\x3', '\x2', '\x2', '\x2', '\x66', 
		'\x64', '\x3', '\x2', '\x2', '\x2', 'g', 'k', '\a', '%', '\x2', '\x2', 
		'h', 'j', '\n', '\x6', '\x2', '\x2', 'i', 'h', '\x3', '\x2', '\x2', '\x2', 
		'j', 'm', '\x3', '\x2', '\x2', '\x2', 'k', 'i', '\x3', '\x2', '\x2', '\x2', 
		'k', 'l', '\x3', '\x2', '\x2', '\x2', 'l', 'n', '\x3', '\x2', '\x2', '\x2', 
		'm', 'k', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\b', '\n', '\x2', '\x2', 
		'o', '\x14', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', 'I', '\x2', '\x2', 
		'q', 'r', '\a', 'k', '\x2', '\x2', 'r', 's', '\a', 'x', '\x2', '\x2', 
		's', 't', '\a', 'g', '\x2', '\x2', 't', 'u', '\a', 'p', '\x2', '\x2', 
		'u', 'v', '\a', '\"', '\x2', '\x2', 'v', '\x16', '\x3', '\x2', '\x2', 
		'\x2', 'w', 'x', '\a', 'Y', '\x2', '\x2', 'x', 'y', '\a', 'j', '\x2', 
		'\x2', 'y', 'z', '\a', 'g', '\x2', '\x2', 'z', '{', '\a', 'p', '\x2', 
		'\x2', '{', '|', '\a', '\"', '\x2', '\x2', '|', '\x18', '\x3', '\x2', 
		'\x2', '\x2', '}', '~', '\a', 'V', '\x2', '\x2', '~', '\x7F', '\a', 'j', 
		'\x2', '\x2', '\x7F', '\x80', '\a', 'g', '\x2', '\x2', '\x80', '\x81', 
		'\a', 'p', '\x2', '\x2', '\x81', '\x82', '\a', '\"', '\x2', '\x2', '\x82', 
		'\x1A', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', '\a', '\x43', '\x2', 
		'\x2', '\x84', '\x85', '\a', 'p', '\x2', '\x2', '\x85', '\x86', '\a', 
		'\x66', '\x2', '\x2', '\x86', '\x87', '\a', '\"', '\x2', '\x2', '\x87', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '\v', '\x2', '\x41', 'I', 'O', 'S', 
		'Z', '_', '\x64', 'k', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace AutoStep.Compiler.Parser
