//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoStep.Definitions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefinitionsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefinitionsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoStep.Definitions.DefinitionsMessages", typeof(DefinitionsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking in type &apos;{0}&apos; for steps..
        /// </summary>
        internal static string AssemblyStepDefinitionSource_LookingInTypeForSteps {
            get {
                return ResourceManager.GetString("AssemblyStepDefinitionSource_LookingInTypeForSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found step method, declared as &apos;{0} {1}&apos; on &apos;{2}&apos;.
        /// </summary>
        internal static string ClassBackedStepDefinitionSource_FoundStepMethod {
            get {
                return ResourceManager.GetString("ClassBackedStepDefinitionSource_FoundStepMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided type must be a class..
        /// </summary>
        internal static string ClassBackedStepDefinitionSource_ProvidedTypeMustBeClass {
            get {
                return ResourceManager.GetString("ClassBackedStepDefinitionSource_ProvidedTypeMustBeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided type &apos;{0}&apos; cannot be abstract..
        /// </summary>
        internal static string ClassStepDefinitionSource_ProvidedTypeCannotBeAbstract {
            get {
                return ResourceManager.GetString("ClassStepDefinitionSource_ProvidedTypeCannotBeAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided type &apos;{0}&apos; has already been added..
        /// </summary>
        internal static string ClassStepDefinitionSource_TypeAlreadyProvided {
            get {
                return ResourceManager.GetString("ClassStepDefinitionSource_TypeAlreadyProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use provided value &apos;{0}&apos; as an argument to {1}. Cannot cast to expected type {2}..
        /// </summary>
        internal static string DefinedInteractionMethod_CannotCastArgument {
            get {
                return ResourceManager.GetString("DefinedInteractionMethod_CannotCastArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use provided value &apos;{0}&apos; as an argument to {1}. Cannot convert to {2}..
        /// </summary>
        internal static string DefinedInteractionMethod_CannotConvertArgument {
            get {
                return ResourceManager.GetString("DefinedInteractionMethod_CannotConvertArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Interaction Method &apos;{0}&apos; has not been implemented..
        /// </summary>
        internal static string InteractionMethod_InvokeNotImplemented {
            get {
                return ResourceManager.GetString("InteractionMethod_InvokeNotImplemented", resourceCulture);
            }
        }
    }
}
